version: "latest"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: codertc

  redis:
    image: redis:latest
    container_name: redis-server_cache
    ports:
      - "6379:6379"
